/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SAMPLE_SAMPLE_TYPES_H
#define SAMPLE_SAMPLE_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* custom thrift includes */

/* begin types */

/* constants */

/* struct BasicPingArgs */
struct _sampleBasicPingArgs
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _sampleBasicPingArgs sampleBasicPingArgs;

struct _sampleBasicPingArgsClass
{
  ThriftStructClass parent;
};
typedef struct _sampleBasicPingArgsClass sampleBasicPingArgsClass;

GType sample_basic_ping_args_get_type (void);
#define SAMPLE_TYPE_BASIC_PING_ARGS (sample_basic_ping_args_get_type())
#define SAMPLE_BASIC_PING_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLE_TYPE_BASIC_PING_ARGS, sampleBasicPingArgs))
#define SAMPLE_BASIC_PING_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), SAMPLE__TYPE_BASIC_PING_ARGS, sampleBasicPingArgsClass))
#define SAMPLE_IS_BASIC_PING_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLE_TYPE_BASIC_PING_ARGS))
#define SAMPLE_IS_BASIC_PING_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), SAMPLE_TYPE_BASIC_PING_ARGS))
#define SAMPLE_BASIC_PING_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLE_TYPE_BASIC_PING_ARGS, sampleBasicPingArgsClass))

/* struct BasicPingResult */
struct _sampleBasicPingResult
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _sampleBasicPingResult sampleBasicPingResult;

struct _sampleBasicPingResultClass
{
  ThriftStructClass parent;
};
typedef struct _sampleBasicPingResultClass sampleBasicPingResultClass;

GType sample_basic_ping_result_get_type (void);
#define SAMPLE_TYPE_BASIC_PING_RESULT (sample_basic_ping_result_get_type())
#define SAMPLE_BASIC_PING_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLE_TYPE_BASIC_PING_RESULT, sampleBasicPingResult))
#define SAMPLE_BASIC_PING_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), SAMPLE__TYPE_BASIC_PING_RESULT, sampleBasicPingResultClass))
#define SAMPLE_IS_BASIC_PING_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLE_TYPE_BASIC_PING_RESULT))
#define SAMPLE_IS_BASIC_PING_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), SAMPLE_TYPE_BASIC_PING_RESULT))
#define SAMPLE_BASIC_PING_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLE_TYPE_BASIC_PING_RESULT, sampleBasicPingResultClass))

/* struct BasicHelloArgs */
struct _sampleBasicHelloArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * arg;
  gboolean __isset_arg;
};
typedef struct _sampleBasicHelloArgs sampleBasicHelloArgs;

struct _sampleBasicHelloArgsClass
{
  ThriftStructClass parent;
};
typedef struct _sampleBasicHelloArgsClass sampleBasicHelloArgsClass;

GType sample_basic_hello_args_get_type (void);
#define SAMPLE_TYPE_BASIC_HELLO_ARGS (sample_basic_hello_args_get_type())
#define SAMPLE_BASIC_HELLO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLE_TYPE_BASIC_HELLO_ARGS, sampleBasicHelloArgs))
#define SAMPLE_BASIC_HELLO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), SAMPLE__TYPE_BASIC_HELLO_ARGS, sampleBasicHelloArgsClass))
#define SAMPLE_IS_BASIC_HELLO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLE_TYPE_BASIC_HELLO_ARGS))
#define SAMPLE_IS_BASIC_HELLO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), SAMPLE_TYPE_BASIC_HELLO_ARGS))
#define SAMPLE_BASIC_HELLO_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLE_TYPE_BASIC_HELLO_ARGS, sampleBasicHelloArgsClass))

/* struct BasicHelloResult */
struct _sampleBasicHelloResult
{ 
  ThriftStruct parent; 

  /* public */
  gchar * success;
  gboolean __isset_success;
};
typedef struct _sampleBasicHelloResult sampleBasicHelloResult;

struct _sampleBasicHelloResultClass
{
  ThriftStructClass parent;
};
typedef struct _sampleBasicHelloResultClass sampleBasicHelloResultClass;

GType sample_basic_hello_result_get_type (void);
#define SAMPLE_TYPE_BASIC_HELLO_RESULT (sample_basic_hello_result_get_type())
#define SAMPLE_BASIC_HELLO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SAMPLE_TYPE_BASIC_HELLO_RESULT, sampleBasicHelloResult))
#define SAMPLE_BASIC_HELLO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), SAMPLE__TYPE_BASIC_HELLO_RESULT, sampleBasicHelloResultClass))
#define SAMPLE_IS_BASIC_HELLO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SAMPLE_TYPE_BASIC_HELLO_RESULT))
#define SAMPLE_IS_BASIC_HELLO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), SAMPLE_TYPE_BASIC_HELLO_RESULT))
#define SAMPLE_BASIC_HELLO_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SAMPLE_TYPE_BASIC_HELLO_RESULT, sampleBasicHelloResultClass))

#endif /* SAMPLE_SAMPLE_TYPES_H */
